stages:
  - build
  - test
  - package
  - deploy

  build:
    stage: build
    script:
    - npm install dependencies
    - npm run build

  test:
    stages: test
    script:
      - npm test

  package:
    stage: package
    script:
      - echo "Docker image is being built ... "
      - docker build -t myapp .

  deploy:
    stage: deploy
    script:
       - docker push my-app
       - echo "Deploying application"

